name: Deploy React to DigitalOcean

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build React app
        run: npm run build

      - name: Decode SSH key
        run: |
          echo "${{ secrets.SERVER_KEY_BASE64 }}" | base64 -d > private_key
          chmod 600 private_key

      - name: Show decoded SSH key (5 перших рядків)
        run: |
          echo "${{ secrets.SERVER_KEY_BASE64 }}" | base64 -d | head -n 5

      - name: Copy build to server (using decoded key)
        uses: appleboy/scp-action@v0.1.2
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key_path: ./private_key
          source: "build/"
          target: "/var/www/studing-react"